name: Linting
on: [push]

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
        
    - name: Vale Linter
      uses: errata-ai/vale-action@v1.0.1
      with:
        styles:
          https://github.com/errata-ai/Microsoft/releases/latest/download/Microsoft.zip
          https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip
        files: content/en/
        config: https://raw.githubusercontent.com/VS-work/flourish-user-docs/master/.vale.ini
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
